Fix steepest descent callback for boost 1.69
In boost::mpi version 1.69 (default on CentOS/Fedora), reduction
functions taking a user-defined operation expect a struct with an
operator() method. Lambda functions are no longer allowed and
generate a compilation error: "error: use of deleted function
'<lambda(const int&, const int&)>::<lambda>()'".