Temporary fix for OpenMPI linker error
Linking using mpicxx instead of c++ as the linker solves the
`undefined reference to symbol MPI::Datatype::Free()` error
because -lmpi_cxx -lmpi is appended at the end of the linker
command, after the espresso object files and walberla static
libraries.